# Generated by Django 4.0.1 on 2022-01-30 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'FormAPI_Parameters',
                'managed': True,
            },
        ),
    ]
