# Generated by Django 4.0.1 on 2022-09-29 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDataProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'main_data_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=1000)),
                ('user_level', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.BooleanField(default=False)),
                ('form_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FormAPI.reportversion')),
            ],
            options={
                'db_table': 'audit_table',
                'managed': True,
            },
        ),
    ]
