# Generated by Django 4.0.1 on 2022-01-30 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=25)),
                ('summate', models.BooleanField()),
                ('parameters', models.ManyToManyField(to='FormAPI.Parameter')),
            ],
            options={
                'db_table': 'FormAPI_ParameterTree',
                'managed': True,
            },
        ),
    ]
