# Generated by Django 4.0.1 on 2022-01-30 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0003_parametertree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.TextField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Quarterly')])),
                ('cutoff', models.IntegerField()),
                ('companies', models.ManyToManyField(to='FormAPI.Company')),
                ('parameters', models.ManyToManyField(to='FormAPI.ParameterTree')),
            ],
            options={
                'db_table': 'FormAPI_Report',
                'managed': True,
            },
        ),
    ]
