# Generated by Django 4.0.1 on 2022-02-01 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0006_alter_reportresult_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('current_value', models.IntegerField()),
                ('last_value', models.IntegerField()),
                ('sub_question', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'FormAPI_sub_questions',
                'managed': True,
            },
        ),
    ]
