# Generated by Django 4.0.1 on 2022-02-01 12:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0007_sub_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('aggregate', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('sub_questions', models.ManyToManyField(to='FormAPI.sub_questions')),
            ],
            options={
                'db_table': 'FormAPI_questions',
                'managed': True,
            },
        ),
    ]
