# Generated by Django 4.0.1 on 2022-02-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0008_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='questionsModel',
        ),
        migrations.RenameModel(
            old_name='sub_questions',
            new_name='sub_questionsModel',
        ),
    ]
