# Generated by Django 4.0.1 on 2022-02-02 05:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0009_rename_questions_questionsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='insideFormModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('deadline_days', models.IntegerField()),
                ('filled_count', models.IntegerField()),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(max_length=255)),
                ('question_count', models.IntegerField()),
                ('schedule', models.CharField(max_length=255)),
                ('is_submitted', models.BooleanField(default=True)),
                ('current_instance', models.JSONField()),
                ('questions', models.ManyToManyField(to='FormAPI.questionsModel')),
            ],
            options={
                'db_table': 'FormAPI_insideFormModel',
                'managed': True,
            },
        ),
    ]
