# Generated by Django 4.0.1 on 2022-03-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0010_insideformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportversion',
            name='comapny',
            field=models.CharField(default='testCompany', max_length=255),
        ),
    ]
