# Generated by Django 4.0.1 on 2022-03-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0011_reportversion_comapny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportversion',
            old_name='comapny',
            new_name='company',
        ),
    ]
