# Generated by Django 4.0.1 on 2022-03-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0012_rename_comapny_reportversion_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportresult',
            name='parametertree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='FormAPI.parametertree'),
        ),
    ]
