# Generated by Django 4.0.1 on 2022-03-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0013_reportresult_parametertree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportresult',
            name='parametertree',
            field=models.ForeignKey(default='4bd10dec-e812-479a-99bf-4f3deda81fe0', on_delete=django.db.models.deletion.PROTECT, to='FormAPI.parametertree'),
        ),
    ]
