# Generated by Django 4.0.1 on 2022-03-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormAPI', '0014_alter_reportresult_parametertree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportresult',
            name='report',
        ),
    ]
